# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7214955c7d167befeb19cbea6bdcb367f68ed1300be2236ce381b8e747eb259e154ea22162aef5168f1c11098466f130256e06c8bdd114e1543aae3143217c

test:
  secret_key_base: dd151a7c5a6e1019051f6098b1b90c52d85acbee8a20825b60cae764ed1664bb652cc4991e282ecf641edb5d6087a18c0050bec8dec0da150e17c8e8d170af84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
